apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argo-app-deployment.yaml
- argo-app-service.yaml
namespace: argo-app
images:
- name: ghcr.io/enfojt/argocd-example
  newName: ghcr.io/enfojt/argocd-example
  newTag: 4d8d1babb9210400b9c820dec319b02dda72347e
