apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argo-app-deployment.yaml
- argo-app-service.yaml
namespace: argo-app
images:
- name: ghcr.io/enfojt/argocd-example
  newName: enfojt/argocd-example
  newTag: b4d3da1238d1515bb6f3b21b21f210ce84df8cc5
