apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- argo-app-deployment.yaml
- argo-app-service.yaml
namespace: argo-app
images:
- name: argo-app
  newName: enfojt/argo-app
  newTag: 5a51b86e82f7d3ca55bca5b6f1ff9d11b4700940
